apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bigbang
  namespace: bigbang
spec:
  interval: 1m
  chart:
    spec:
      chart: bigbang
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: registry1
      verify:
        provider: cosign
        secretRef:
          name: bigbang-cosign-pub
### valuesFrom bottom takes precedence over top i.e common-bb-secret overwrites common-bb
  valuesFrom:
    - kind: ConfigMap
      name: common-bb
      valuesKey: values.yaml
    - kind: Secret
      name: common-bb-secret
      valuesKey: values.yaml