configMapGenerator:
- behavior: merge
  files:
  - values.yaml=configmap.yaml
  name: environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
# # Enable the line below if a secrets.enc.yaml is created in this directory
# - path: secrets.enc.yaml
- patch: |-
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: bigbang
    spec:
      interval: 1m
  # Use the following three lines to test a new version of Big Bang without affecting other environments
  #   ref:
  #     $patch: replace
  #     tag: "2.53.1"
- patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: bigbang
    spec:
      interval: 1m
