apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- configmap.yaml
- secrets/staging-bb-secret.enc.yaml
patches:
- target:
    kind: HelmRelease
    name: bigbang
  patch: |-
    - op: add
      path: /spec/valuesFrom/-
      value:
        kind: ConfigMap
        name: staging-bb
        valuesKey: values.yaml
    - op: add
      path: /spec/valuesFrom/-
      value:
        kind: Secret
        name: staging-bb-secret
        valuesKey: values.yaml
