# When updating the version of BigBang, make sure to update
#   both the bases reference and the GitRepository reference
bases:
- https://repo1.dso.mil/platform-one/big-bang/bigbang.git/base?ref=2.24.0
# - helmrepo.yaml
# - cosignsecret.yaml
configMapGenerator:
  - name: common
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patchesStrategicMerge:
- secrets.enc.yaml
# Enable this section if you wish to use the OCI HelmRepo with Cosign Verfiy instead of the GitRepository.
# - |-
#   apiVersion: helm.toolkit.fluxcd.io/v2beta2
#   kind: HelmRelease
#   metadata:
#     name: bigbang
#   spec:
#     interval: 1m
#     chart:
#       spec:
#         chart: bigbang
#         version: 2.24.0
#         sourceRef:
#           kind: HelmRepository
#           name: registry1
#         verify:
#           provider: cosign
#           secretRef:
#             name: bigbang-cosign-pub
